// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// EventsOKCode is the HTTP code returned for type EventsOK
const EventsOKCode int = 200

/*EventsOK OK

swagger:response eventsOK
*/
type EventsOK struct {
}

// NewEventsOK creates EventsOK with default headers values
func NewEventsOK() *EventsOK {

	return &EventsOK{}
}

// WriteResponse to the client
func (o *EventsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
