// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetV1PingOKCode is the HTTP code returned for type GetV1PingOK
const GetV1PingOKCode int = 200

/*GetV1PingOK OK

swagger:response getV1PingOK
*/
type GetV1PingOK struct {
}

// NewGetV1PingOK creates GetV1PingOK with default headers values
func NewGetV1PingOK() *GetV1PingOK {

	return &GetV1PingOK{}
}

// WriteResponse to the client
func (o *GetV1PingOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
