const KAFKA_BOOTSTRAP_SERVER = process.env.KAFKA_BOOTSTRAP_SERVERS || 'localhost:9092';
const KAFKA_CONSUMER_SESSION_TIMEOUT = 300000; // in ms
const CERTIFY_TOPIC = 'certify';
const REGISTRY_URL = process.env.REGISTRY_URL || 'http://localhost:8081';
const CERTIFIED_TOPIC = 'certified';
const ERROR_CERTIFICATE_TOPIC = 'error_certificate';
const SMS_GATEWAY_URL = 'https://api.msg91.com/api/v2/sendsms';
const ENABLE_SMS_NOTIFICATION = false;
const ENABLE_CERTIFY_ACKNOWLEDGEMENT = process.env.ENABLE_CERTIFY_ACKNOWLEDGEMENT || true;
const CERTIFICATE_RETRY_COUNT = process.env.CERTIFICATE_RETRY_COUNT || 5;
module.exports = {
  KAFKA_BOOTSTRAP_SERVER,
  CERTIFY_TOPIC,
  REGISTRY_URL,
  CERTIFIED_TOPIC,
  SMS_GATEWAY_URL,
  ENABLE_SMS_NOTIFICATION,
  ENABLE_CERTIFY_ACKNOWLEDGEMENT,
  ERROR_CERTIFICATE_TOPIC,
  CERTIFICATE_RETRY_COUNT,
  KAFKA_CONSUMER_SESSION_TIMEOUT
};
