const CONFIG_KEYS = {
  ICD: "ICD",
  VACCINE_ICD: "VACCINE_ICD",
  FIELDS_KEY_PATH: "fieldsKeyPath",
  DDCC_TEMPLATE: "DDCC_TEMPLATE",
  W3C_TEMPLATE: "W3C_TEMPLATE"
};
Object.freeze(CONFIG_KEYS);

module.exports = {
  CONFIG_KEYS
}