// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// CreateProgramOKCode is the HTTP code returned for type CreateProgramOK
const CreateProgramOKCode int = 200

/*CreateProgramOK OK

swagger:response createProgramOK
*/
type CreateProgramOK struct {
}

// NewCreateProgramOK creates CreateProgramOK with default headers values
func NewCreateProgramOK() *CreateProgramOK {

	return &CreateProgramOK{}
}

// WriteResponse to the client
func (o *CreateProgramOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// CreateProgramBadRequestCode is the HTTP code returned for type CreateProgramBadRequest
const CreateProgramBadRequestCode int = 400

/*CreateProgramBadRequest Invalid input

swagger:response createProgramBadRequest
*/
type CreateProgramBadRequest struct {
}

// NewCreateProgramBadRequest creates CreateProgramBadRequest with default headers values
func NewCreateProgramBadRequest() *CreateProgramBadRequest {

	return &CreateProgramBadRequest{}
}

// WriteResponse to the client
func (o *CreateProgramBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// CreateProgramUnauthorizedCode is the HTTP code returned for type CreateProgramUnauthorized
const CreateProgramUnauthorizedCode int = 401

/*CreateProgramUnauthorized Unauthorized

swagger:response createProgramUnauthorized
*/
type CreateProgramUnauthorized struct {
}

// NewCreateProgramUnauthorized creates CreateProgramUnauthorized with default headers values
func NewCreateProgramUnauthorized() *CreateProgramUnauthorized {

	return &CreateProgramUnauthorized{}
}

// WriteResponse to the client
func (o *CreateProgramUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}
