// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetFacilitiesForPublicHandlerFunc turns a function with the right signature into a get facilities for public handler
type GetFacilitiesForPublicHandlerFunc func(GetFacilitiesForPublicParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetFacilitiesForPublicHandlerFunc) Handle(params GetFacilitiesForPublicParams) middleware.Responder {
	return fn(params)
}

// GetFacilitiesForPublicHandler interface for that can handle valid get facilities for public params
type GetFacilitiesForPublicHandler interface {
	Handle(GetFacilitiesForPublicParams) middleware.Responder
}

// NewGetFacilitiesForPublic creates a new http.Handler for the get facilities for public operation
func NewGetFacilitiesForPublic(ctx *middleware.Context, handler GetFacilitiesForPublicHandler) *GetFacilitiesForPublic {
	return &GetFacilitiesForPublic{Context: ctx, Handler: handler}
}

/* GetFacilitiesForPublic swagger:route GET /public/facilities getFacilitiesForPublic

get facilities for public

*/
type GetFacilitiesForPublic struct {
	Context *middleware.Context
	Handler GetFacilitiesForPublicHandler
}

func (o *GetFacilitiesForPublic) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetFacilitiesForPublicParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
