// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/divoc/portal-api/swagger_gen/models"
)

// GetFacilitiesHandlerFunc turns a function with the right signature into a get facilities handler
type GetFacilitiesHandlerFunc func(GetFacilitiesParams, *models.JWTClaimBody) middleware.Responder

// Handle executing the request and returning a response
func (fn GetFacilitiesHandlerFunc) Handle(params GetFacilitiesParams, principal *models.JWTClaimBody) middleware.Responder {
	return fn(params, principal)
}

// GetFacilitiesHandler interface for that can handle valid get facilities params
type GetFacilitiesHandler interface {
	Handle(GetFacilitiesParams, *models.JWTClaimBody) middleware.Responder
}

// NewGetFacilities creates a new http.Handler for the get facilities operation
func NewGetFacilities(ctx *middleware.Context, handler GetFacilitiesHandler) *GetFacilities {
	return &GetFacilities{Context: ctx, Handler: handler}
}

/* GetFacilities swagger:route GET /facilities getFacilities

get facilities

*/
type GetFacilities struct {
	Context *middleware.Context
	Handler GetFacilitiesHandler
}

func (o *GetFacilities) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetFacilitiesParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.JWTClaimBody
	if uprinc != nil {
		principal = uprinc.(*models.JWTClaimBody) // this is really a models.JWTClaimBody, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
