// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetFacilityUploadsErrorsOKCode is the HTTP code returned for type GetFacilityUploadsErrorsOK
const GetFacilityUploadsErrorsOKCode int = 200

/*GetFacilityUploadsErrorsOK OK

swagger:response getFacilityUploadsErrorsOK
*/
type GetFacilityUploadsErrorsOK struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewGetFacilityUploadsErrorsOK creates GetFacilityUploadsErrorsOK with default headers values
func NewGetFacilityUploadsErrorsOK() *GetFacilityUploadsErrorsOK {

	return &GetFacilityUploadsErrorsOK{}
}

// WithPayload adds the payload to the get facility uploads errors o k response
func (o *GetFacilityUploadsErrorsOK) WithPayload(payload interface{}) *GetFacilityUploadsErrorsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get facility uploads errors o k response
func (o *GetFacilityUploadsErrorsOK) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetFacilityUploadsErrorsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetFacilityUploadsErrorsForbiddenCode is the HTTP code returned for type GetFacilityUploadsErrorsForbidden
const GetFacilityUploadsErrorsForbiddenCode int = 403

/*GetFacilityUploadsErrorsForbidden Forbidden for user

swagger:response getFacilityUploadsErrorsForbidden
*/
type GetFacilityUploadsErrorsForbidden struct {
}

// NewGetFacilityUploadsErrorsForbidden creates GetFacilityUploadsErrorsForbidden with default headers values
func NewGetFacilityUploadsErrorsForbidden() *GetFacilityUploadsErrorsForbidden {

	return &GetFacilityUploadsErrorsForbidden{}
}

// WriteResponse to the client
func (o *GetFacilityUploadsErrorsForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// GetFacilityUploadsErrorsNotFoundCode is the HTTP code returned for type GetFacilityUploadsErrorsNotFound
const GetFacilityUploadsErrorsNotFoundCode int = 404

/*GetFacilityUploadsErrorsNotFound facility upload for given uploadID not found

swagger:response getFacilityUploadsErrorsNotFound
*/
type GetFacilityUploadsErrorsNotFound struct {
}

// NewGetFacilityUploadsErrorsNotFound creates GetFacilityUploadsErrorsNotFound with default headers values
func NewGetFacilityUploadsErrorsNotFound() *GetFacilityUploadsErrorsNotFound {

	return &GetFacilityUploadsErrorsNotFound{}
}

// WriteResponse to the client
func (o *GetFacilityUploadsErrorsNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
