// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetAnalyticsOKCode is the HTTP code returned for type GetAnalyticsOK
const GetAnalyticsOKCode int = 200

/*GetAnalyticsOK OK

swagger:response getAnalyticsOK
*/
type GetAnalyticsOK struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewGetAnalyticsOK creates GetAnalyticsOK with default headers values
func NewGetAnalyticsOK() *GetAnalyticsOK {

	return &GetAnalyticsOK{}
}

// WithPayload adds the payload to the get analytics o k response
func (o *GetAnalyticsOK) WithPayload(payload interface{}) *GetAnalyticsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get analytics o k response
func (o *GetAnalyticsOK) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAnalyticsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetAnalyticsUnauthorizedCode is the HTTP code returned for type GetAnalyticsUnauthorized
const GetAnalyticsUnauthorizedCode int = 401

/*GetAnalyticsUnauthorized Unauthorized

swagger:response getAnalyticsUnauthorized
*/
type GetAnalyticsUnauthorized struct {
}

// NewGetAnalyticsUnauthorized creates GetAnalyticsUnauthorized with default headers values
func NewGetAnalyticsUnauthorized() *GetAnalyticsUnauthorized {

	return &GetAnalyticsUnauthorized{}
}

// WriteResponse to the client
func (o *GetAnalyticsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}
