// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/divoc/portal-api/swagger_gen/models"
)

// GetFacilityGroupsHandlerFunc turns a function with the right signature into a get facility groups handler
type GetFacilityGroupsHandlerFunc func(GetFacilityGroupsParams, *models.JWTClaimBody) middleware.Responder

// Handle executing the request and returning a response
func (fn GetFacilityGroupsHandlerFunc) Handle(params GetFacilityGroupsParams, principal *models.JWTClaimBody) middleware.Responder {
	return fn(params, principal)
}

// GetFacilityGroupsHandler interface for that can handle valid get facility groups params
type GetFacilityGroupsHandler interface {
	Handle(GetFacilityGroupsParams, *models.JWTClaimBody) middleware.Responder
}

// NewGetFacilityGroups creates a new http.Handler for the get facility groups operation
func NewGetFacilityGroups(ctx *middleware.Context, handler GetFacilityGroupsHandler) *GetFacilityGroups {
	return &GetFacilityGroups{Context: ctx, Handler: handler}
}

/*GetFacilityGroups swagger:route GET /facility/groups getFacilityGroups

Get facility groups

*/
type GetFacilityGroups struct {
	Context *middleware.Context
	Handler GetFacilityGroupsHandler
}

func (o *GetFacilityGroups) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetFacilityGroupsParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.JWTClaimBody
	if uprinc != nil {
		principal = uprinc.(*models.JWTClaimBody) // this is really a models.JWTClaimBody, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
