// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/divoc/portal-api/swagger_gen/models"
)

// GetFacilityProgramScheduleOKCode is the HTTP code returned for type GetFacilityProgramScheduleOK
const GetFacilityProgramScheduleOKCode int = 200

/*GetFacilityProgramScheduleOK OK

swagger:response getFacilityProgramScheduleOK
*/
type GetFacilityProgramScheduleOK struct {

	/*
	  In: Body
	*/
	Payload *models.FacilityConfigureSlot `json:"body,omitempty"`
}

// NewGetFacilityProgramScheduleOK creates GetFacilityProgramScheduleOK with default headers values
func NewGetFacilityProgramScheduleOK() *GetFacilityProgramScheduleOK {

	return &GetFacilityProgramScheduleOK{}
}

// WithPayload adds the payload to the get facility program schedule o k response
func (o *GetFacilityProgramScheduleOK) WithPayload(payload *models.FacilityConfigureSlot) *GetFacilityProgramScheduleOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get facility program schedule o k response
func (o *GetFacilityProgramScheduleOK) SetPayload(payload *models.FacilityConfigureSlot) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetFacilityProgramScheduleOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetFacilityProgramScheduleBadRequestCode is the HTTP code returned for type GetFacilityProgramScheduleBadRequest
const GetFacilityProgramScheduleBadRequestCode int = 400

/*GetFacilityProgramScheduleBadRequest Invalid input

swagger:response getFacilityProgramScheduleBadRequest
*/
type GetFacilityProgramScheduleBadRequest struct {
}

// NewGetFacilityProgramScheduleBadRequest creates GetFacilityProgramScheduleBadRequest with default headers values
func NewGetFacilityProgramScheduleBadRequest() *GetFacilityProgramScheduleBadRequest {

	return &GetFacilityProgramScheduleBadRequest{}
}

// WriteResponse to the client
func (o *GetFacilityProgramScheduleBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetFacilityProgramScheduleUnauthorizedCode is the HTTP code returned for type GetFacilityProgramScheduleUnauthorized
const GetFacilityProgramScheduleUnauthorizedCode int = 401

/*GetFacilityProgramScheduleUnauthorized Unauthorized

swagger:response getFacilityProgramScheduleUnauthorized
*/
type GetFacilityProgramScheduleUnauthorized struct {
}

// NewGetFacilityProgramScheduleUnauthorized creates GetFacilityProgramScheduleUnauthorized with default headers values
func NewGetFacilityProgramScheduleUnauthorized() *GetFacilityProgramScheduleUnauthorized {

	return &GetFacilityProgramScheduleUnauthorized{}
}

// WriteResponse to the client
func (o *GetFacilityProgramScheduleUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// GetFacilityProgramScheduleNotFoundCode is the HTTP code returned for type GetFacilityProgramScheduleNotFound
const GetFacilityProgramScheduleNotFoundCode int = 404

/*GetFacilityProgramScheduleNotFound schedult for given facility and program not found

swagger:response getFacilityProgramScheduleNotFound
*/
type GetFacilityProgramScheduleNotFound struct {
}

// NewGetFacilityProgramScheduleNotFound creates GetFacilityProgramScheduleNotFound with default headers values
func NewGetFacilityProgramScheduleNotFound() *GetFacilityProgramScheduleNotFound {

	return &GetFacilityProgramScheduleNotFound{}
}

// WriteResponse to the client
func (o *GetFacilityProgramScheduleNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
