// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetProgramsForPublicHandlerFunc turns a function with the right signature into a get programs for public handler
type GetProgramsForPublicHandlerFunc func(GetProgramsForPublicParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetProgramsForPublicHandlerFunc) Handle(params GetProgramsForPublicParams) middleware.Responder {
	return fn(params)
}

// GetProgramsForPublicHandler interface for that can handle valid get programs for public params
type GetProgramsForPublicHandler interface {
	Handle(GetProgramsForPublicParams) middleware.Responder
}

// NewGetProgramsForPublic creates a new http.Handler for the get programs for public operation
func NewGetProgramsForPublic(ctx *middleware.Context, handler GetProgramsForPublicHandler) *GetProgramsForPublic {
	return &GetProgramsForPublic{Context: ctx, Handler: handler}
}

/* GetProgramsForPublic swagger:route GET /public/programs getProgramsForPublic

get program list for public

*/
type GetProgramsForPublic struct {
	Context *middleware.Context
	Handler GetProgramsForPublicHandler
}

func (o *GetProgramsForPublic) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetProgramsForPublicParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
