// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/divoc/portal-api/swagger_gen/models"
)

// GetFacilitySchedulesOKCode is the HTTP code returned for type GetFacilitySchedulesOK
const GetFacilitySchedulesOKCode int = 200

/*GetFacilitySchedulesOK OK

swagger:response getFacilitySchedulesOK
*/
type GetFacilitySchedulesOK struct {

	/*
	  In: Body
	*/
	Payload []*models.FacilityConfigureSlot `json:"body,omitempty"`
}

// NewGetFacilitySchedulesOK creates GetFacilitySchedulesOK with default headers values
func NewGetFacilitySchedulesOK() *GetFacilitySchedulesOK {

	return &GetFacilitySchedulesOK{}
}

// WithPayload adds the payload to the get facility schedules o k response
func (o *GetFacilitySchedulesOK) WithPayload(payload []*models.FacilityConfigureSlot) *GetFacilitySchedulesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get facility schedules o k response
func (o *GetFacilitySchedulesOK) SetPayload(payload []*models.FacilityConfigureSlot) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetFacilitySchedulesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.FacilityConfigureSlot, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetFacilitySchedulesBadRequestCode is the HTTP code returned for type GetFacilitySchedulesBadRequest
const GetFacilitySchedulesBadRequestCode int = 400

/*GetFacilitySchedulesBadRequest Invalid input

swagger:response getFacilitySchedulesBadRequest
*/
type GetFacilitySchedulesBadRequest struct {
}

// NewGetFacilitySchedulesBadRequest creates GetFacilitySchedulesBadRequest with default headers values
func NewGetFacilitySchedulesBadRequest() *GetFacilitySchedulesBadRequest {

	return &GetFacilitySchedulesBadRequest{}
}

// WriteResponse to the client
func (o *GetFacilitySchedulesBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetFacilitySchedulesUnauthorizedCode is the HTTP code returned for type GetFacilitySchedulesUnauthorized
const GetFacilitySchedulesUnauthorizedCode int = 401

/*GetFacilitySchedulesUnauthorized Unauthorized

swagger:response getFacilitySchedulesUnauthorized
*/
type GetFacilitySchedulesUnauthorized struct {
}

// NewGetFacilitySchedulesUnauthorized creates GetFacilitySchedulesUnauthorized with default headers values
func NewGetFacilitySchedulesUnauthorized() *GetFacilitySchedulesUnauthorized {

	return &GetFacilitySchedulesUnauthorized{}
}

// WriteResponse to the client
func (o *GetFacilitySchedulesUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// GetFacilitySchedulesNotFoundCode is the HTTP code returned for type GetFacilitySchedulesNotFound
const GetFacilitySchedulesNotFoundCode int = 404

/*GetFacilitySchedulesNotFound schedule for given facility not found

swagger:response getFacilitySchedulesNotFound
*/
type GetFacilitySchedulesNotFound struct {
}

// NewGetFacilitySchedulesNotFound creates GetFacilitySchedulesNotFound with default headers values
func NewGetFacilitySchedulesNotFound() *GetFacilitySchedulesNotFound {

	return &GetFacilitySchedulesNotFound{}
}

// WriteResponse to the client
func (o *GetFacilitySchedulesNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
