// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// NotifyFacilitiesOKCode is the HTTP code returned for type NotifyFacilitiesOK
const NotifyFacilitiesOKCode int = 200

/*NotifyFacilitiesOK OK

swagger:response notifyFacilitiesOK
*/
type NotifyFacilitiesOK struct {

	/*
	  In: Body
	*/
	Payload []interface{} `json:"body,omitempty"`
}

// NewNotifyFacilitiesOK creates NotifyFacilitiesOK with default headers values
func NewNotifyFacilitiesOK() *NotifyFacilitiesOK {

	return &NotifyFacilitiesOK{}
}

// WithPayload adds the payload to the notify facilities o k response
func (o *NotifyFacilitiesOK) WithPayload(payload []interface{}) *NotifyFacilitiesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the notify facilities o k response
func (o *NotifyFacilitiesOK) SetPayload(payload []interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NotifyFacilitiesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]interface{}, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
