// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostFacilitiesOKCode is the HTTP code returned for type PostFacilitiesOK
const PostFacilitiesOKCode int = 200

/*PostFacilitiesOK OK

swagger:response postFacilitiesOK
*/
type PostFacilitiesOK struct {
}

// NewPostFacilitiesOK creates PostFacilitiesOK with default headers values
func NewPostFacilitiesOK() *PostFacilitiesOK {

	return &PostFacilitiesOK{}
}

// WriteResponse to the client
func (o *PostFacilitiesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PostFacilitiesBadRequestCode is the HTTP code returned for type PostFacilitiesBadRequest
const PostFacilitiesBadRequestCode int = 400

/*PostFacilitiesBadRequest Invalid input

swagger:response postFacilitiesBadRequest
*/
type PostFacilitiesBadRequest struct {
}

// NewPostFacilitiesBadRequest creates PostFacilitiesBadRequest with default headers values
func NewPostFacilitiesBadRequest() *PostFacilitiesBadRequest {

	return &PostFacilitiesBadRequest{}
}

// WriteResponse to the client
func (o *PostFacilitiesBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// PostFacilitiesUnauthorizedCode is the HTTP code returned for type PostFacilitiesUnauthorized
const PostFacilitiesUnauthorizedCode int = 401

/*PostFacilitiesUnauthorized Unauthorized

swagger:response postFacilitiesUnauthorized
*/
type PostFacilitiesUnauthorized struct {
}

// NewPostFacilitiesUnauthorized creates PostFacilitiesUnauthorized with default headers values
func NewPostFacilitiesUnauthorized() *PostFacilitiesUnauthorized {

	return &PostFacilitiesUnauthorized{}
}

// WriteResponse to the client
func (o *PostFacilitiesUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}
