// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// UpdateVaccinatorsOKCode is the HTTP code returned for type UpdateVaccinatorsOK
const UpdateVaccinatorsOKCode int = 200

/*UpdateVaccinatorsOK OK

swagger:response updateVaccinatorsOK
*/
type UpdateVaccinatorsOK struct {
}

// NewUpdateVaccinatorsOK creates UpdateVaccinatorsOK with default headers values
func NewUpdateVaccinatorsOK() *UpdateVaccinatorsOK {

	return &UpdateVaccinatorsOK{}
}

// WriteResponse to the client
func (o *UpdateVaccinatorsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// UpdateVaccinatorsBadRequestCode is the HTTP code returned for type UpdateVaccinatorsBadRequest
const UpdateVaccinatorsBadRequestCode int = 400

/*UpdateVaccinatorsBadRequest Invalid input

swagger:response updateVaccinatorsBadRequest
*/
type UpdateVaccinatorsBadRequest struct {
}

// NewUpdateVaccinatorsBadRequest creates UpdateVaccinatorsBadRequest with default headers values
func NewUpdateVaccinatorsBadRequest() *UpdateVaccinatorsBadRequest {

	return &UpdateVaccinatorsBadRequest{}
}

// WriteResponse to the client
func (o *UpdateVaccinatorsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// UpdateVaccinatorsUnauthorizedCode is the HTTP code returned for type UpdateVaccinatorsUnauthorized
const UpdateVaccinatorsUnauthorizedCode int = 401

/*UpdateVaccinatorsUnauthorized Unauthorized

swagger:response updateVaccinatorsUnauthorized
*/
type UpdateVaccinatorsUnauthorized struct {
}

// NewUpdateVaccinatorsUnauthorized creates UpdateVaccinatorsUnauthorized with default headers values
func NewUpdateVaccinatorsUnauthorized() *UpdateVaccinatorsUnauthorized {

	return &UpdateVaccinatorsUnauthorized{}
}

// WriteResponse to the client
func (o *UpdateVaccinatorsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}
