// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/divoc/portal-api/swagger_gen/models"
)

// UpdateProgramHandlerFunc turns a function with the right signature into a update program handler
type UpdateProgramHandlerFunc func(UpdateProgramParams, *models.JWTClaimBody) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateProgramHandlerFunc) Handle(params UpdateProgramParams, principal *models.JWTClaimBody) middleware.Responder {
	return fn(params, principal)
}

// UpdateProgramHandler interface for that can handle valid update program params
type UpdateProgramHandler interface {
	Handle(UpdateProgramParams, *models.JWTClaimBody) middleware.Responder
}

// NewUpdateProgram creates a new http.Handler for the update program operation
func NewUpdateProgram(ctx *middleware.Context, handler UpdateProgramHandler) *UpdateProgram {
	return &UpdateProgram{Context: ctx, Handler: handler}
}

/*UpdateProgram swagger:route PUT /programs updateProgram

Update program

*/
type UpdateProgram struct {
	Context *middleware.Context
	Handler UpdateProgramHandler
}

func (o *UpdateProgram) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUpdateProgramParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.JWTClaimBody
	if uprinc != nil {
		principal = uprinc.(*models.JWTClaimBody) // this is really a models.JWTClaimBody, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
