// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Registration adapter API
//
//  Registration adapter API
//  Schemes:
//    https
//  Host: localhost
//  BasePath: /api/v1
//  Version: 1.0.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
