apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: certificate-api
  name: certificate-api
spec:
  ports:
    - name: "tcp-4321"
      port: 4321
      protocol: TCP
      targetPort: 4321
      nodePort: 32321
  selector:
    k8s-app: certificate-api
  sessionAffinity: None
  type: NodePort