apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: test-certificate-signer
  name: test-certificate-signer
spec:
  externalTrafficPolicy: Cluster
  selector:
    k8s-app: test-certificate-signer
  sessionAffinity: None
  type: ClusterIP