// Code generated by go-swagger; DO NOT EDIT.

package vaccination

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/divoc/api/swagger_gen/models"
)

// GetPreEnrollmentOKCode is the HTTP code returned for type GetPreEnrollmentOK
const GetPreEnrollmentOKCode int = 200

/*GetPreEnrollmentOK OK

swagger:response getPreEnrollmentOK
*/
type GetPreEnrollmentOK struct {

	/*
	  In: Body
	*/
	Payload *models.PreEnrollment `json:"body,omitempty"`
}

// NewGetPreEnrollmentOK creates GetPreEnrollmentOK with default headers values
func NewGetPreEnrollmentOK() *GetPreEnrollmentOK {

	return &GetPreEnrollmentOK{}
}

// WithPayload adds the payload to the get pre enrollment o k response
func (o *GetPreEnrollmentOK) WithPayload(payload *models.PreEnrollment) *GetPreEnrollmentOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get pre enrollment o k response
func (o *GetPreEnrollmentOK) SetPayload(payload *models.PreEnrollment) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPreEnrollmentOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
