// Code generated by go-swagger; DO NOT EDIT.

package identity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostV1IdentityVerifyOKCode is the HTTP code returned for type PostV1IdentityVerifyOK
const PostV1IdentityVerifyOKCode int = 200

/*PostV1IdentityVerifyOK OK

swagger:response postV1IdentityVerifyOK
*/
type PostV1IdentityVerifyOK struct {
}

// NewPostV1IdentityVerifyOK creates PostV1IdentityVerifyOK with default headers values
func NewPostV1IdentityVerifyOK() *PostV1IdentityVerifyOK {

	return &PostV1IdentityVerifyOK{}
}

// WriteResponse to the client
func (o *PostV1IdentityVerifyOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PostV1IdentityVerifyPartialContentCode is the HTTP code returned for type PostV1IdentityVerifyPartialContent
const PostV1IdentityVerifyPartialContentCode int = 206

/*PostV1IdentityVerifyPartialContent Need OTP

swagger:response postV1IdentityVerifyPartialContent
*/
type PostV1IdentityVerifyPartialContent struct {
}

// NewPostV1IdentityVerifyPartialContent creates PostV1IdentityVerifyPartialContent with default headers values
func NewPostV1IdentityVerifyPartialContent() *PostV1IdentityVerifyPartialContent {

	return &PostV1IdentityVerifyPartialContent{}
}

// WriteResponse to the client
func (o *PostV1IdentityVerifyPartialContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(206)
}
