// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CancelAppointmentHandlerFunc turns a function with the right signature into a cancel appointment handler
type CancelAppointmentHandlerFunc func(CancelAppointmentParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CancelAppointmentHandlerFunc) Handle(params CancelAppointmentParams) middleware.Responder {
	return fn(params)
}

// CancelAppointmentHandler interface for that can handle valid cancel appointment params
type CancelAppointmentHandler interface {
	Handle(CancelAppointmentParams) middleware.Responder
}

// NewCancelAppointment creates a new http.Handler for the cancel appointment operation
func NewCancelAppointment(ctx *middleware.Context, handler CancelAppointmentHandler) *CancelAppointment {
	return &CancelAppointment{Context: ctx, Handler: handler}
}

/*CancelAppointment swagger:route POST /appointment/cancel cancelAppointment

cancel an appointment

*/
type CancelAppointment struct {
	Context *middleware.Context
	Handler CancelAppointmentHandler
}

func (o *CancelAppointment) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCancelAppointmentParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// CancelAppointmentBody cancel appointment body
//
// swagger:model CancelAppointmentBody
type CancelAppointmentBody struct {

	// beneficiaries
	// Required: true
	Beneficiaries []string `json:"beneficiaries"`

	// center id
	// Required: true
	CenterID *string `json:"center_id"`

	// date
	// Required: true
	Date *string `json:"date"`

	// slot id
	// Required: true
	SlotID *string `json:"slot_id"`
}

// Validate validates this cancel appointment body
func (o *CancelAppointmentBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateBeneficiaries(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateCenterID(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateDate(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateSlotID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *CancelAppointmentBody) validateBeneficiaries(formats strfmt.Registry) error {

	if err := validate.Required("body"+"."+"beneficiaries", "body", o.Beneficiaries); err != nil {
		return err
	}

	return nil
}

func (o *CancelAppointmentBody) validateCenterID(formats strfmt.Registry) error {

	if err := validate.Required("body"+"."+"center_id", "body", o.CenterID); err != nil {
		return err
	}

	return nil
}

func (o *CancelAppointmentBody) validateDate(formats strfmt.Registry) error {

	if err := validate.Required("body"+"."+"date", "body", o.Date); err != nil {
		return err
	}

	return nil
}

func (o *CancelAppointmentBody) validateSlotID(formats strfmt.Registry) error {

	if err := validate.Required("body"+"."+"slot_id", "body", o.SlotID); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *CancelAppointmentBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CancelAppointmentBody) UnmarshalBinary(b []byte) error {
	var res CancelAppointmentBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
