// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// ConfirmOTPOKCode is the HTTP code returned for type ConfirmOTPOK
const ConfirmOTPOKCode int = 200

/*ConfirmOTPOK OK

swagger:response confirmOTPOK
*/
type ConfirmOTPOK struct {

	/*
	  In: Body
	*/
	Payload *ConfirmOTPOKBody `json:"body,omitempty"`
}

// NewConfirmOTPOK creates ConfirmOTPOK with default headers values
func NewConfirmOTPOK() *ConfirmOTPOK {

	return &ConfirmOTPOK{}
}

// WithPayload adds the payload to the confirm o t p o k response
func (o *ConfirmOTPOK) WithPayload(payload *ConfirmOTPOKBody) *ConfirmOTPOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the confirm o t p o k response
func (o *ConfirmOTPOK) SetPayload(payload *ConfirmOTPOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ConfirmOTPOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ConfirmOTPBadRequestCode is the HTTP code returned for type ConfirmOTPBadRequest
const ConfirmOTPBadRequestCode int = 400

/*ConfirmOTPBadRequest Bad Request

swagger:response confirmOTPBadRequest
*/
type ConfirmOTPBadRequest struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewConfirmOTPBadRequest creates ConfirmOTPBadRequest with default headers values
func NewConfirmOTPBadRequest() *ConfirmOTPBadRequest {

	return &ConfirmOTPBadRequest{}
}

// WithPayload adds the payload to the confirm o t p bad request response
func (o *ConfirmOTPBadRequest) WithPayload(payload interface{}) *ConfirmOTPBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the confirm o t p bad request response
func (o *ConfirmOTPBadRequest) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ConfirmOTPBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// ConfirmOTPUnauthorizedCode is the HTTP code returned for type ConfirmOTPUnauthorized
const ConfirmOTPUnauthorizedCode int = 401

/*ConfirmOTPUnauthorized Unauthorized

swagger:response confirmOTPUnauthorized
*/
type ConfirmOTPUnauthorized struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewConfirmOTPUnauthorized creates ConfirmOTPUnauthorized with default headers values
func NewConfirmOTPUnauthorized() *ConfirmOTPUnauthorized {

	return &ConfirmOTPUnauthorized{}
}

// WithPayload adds the payload to the confirm o t p unauthorized response
func (o *ConfirmOTPUnauthorized) WithPayload(payload interface{}) *ConfirmOTPUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the confirm o t p unauthorized response
func (o *ConfirmOTPUnauthorized) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ConfirmOTPUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// ConfirmOTPTooManyRequestsCode is the HTTP code returned for type ConfirmOTPTooManyRequests
const ConfirmOTPTooManyRequestsCode int = 429

/*ConfirmOTPTooManyRequests Too many requests

swagger:response confirmOTPTooManyRequests
*/
type ConfirmOTPTooManyRequests struct {
}

// NewConfirmOTPTooManyRequests creates ConfirmOTPTooManyRequests with default headers values
func NewConfirmOTPTooManyRequests() *ConfirmOTPTooManyRequests {

	return &ConfirmOTPTooManyRequests{}
}

// WriteResponse to the client
func (o *ConfirmOTPTooManyRequests) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(429)
}
