// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/loads"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/runtime/security"
	"github.com/go-openapi/spec"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewRegistrationAdapterAPIAPI creates a new RegistrationAdapterAPI instance
func NewRegistrationAdapterAPIAPI(spec *loads.Document) *RegistrationAdapterAPIAPI {
	return &RegistrationAdapterAPIAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		PreServerShutdown:   func() {},
		ServerShutdown:      func() {},
		spec:                spec,
		useSwaggerUI:        false,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,

		JSONConsumer: runtime.JSONConsumer(),

		JSONProducer: runtime.JSONProducer(),

		BookAppointmentHandler: BookAppointmentHandlerFunc(func(params BookAppointmentParams) middleware.Responder {
			return middleware.NotImplemented("operation BookAppointment has not yet been implemented")
		}),
		CancelAppointmentHandler: CancelAppointmentHandlerFunc(func(params CancelAppointmentParams) middleware.Responder {
			return middleware.NotImplemented("operation CancelAppointment has not yet been implemented")
		}),
		ConfirmOTPHandler: ConfirmOTPHandlerFunc(func(params ConfirmOTPParams) middleware.Responder {
			return middleware.NotImplemented("operation ConfirmOTP has not yet been implemented")
		}),
		CreateNewBeneficiaryHandler: CreateNewBeneficiaryHandlerFunc(func(params CreateNewBeneficiaryParams) middleware.Responder {
			return middleware.NotImplemented("operation CreateNewBeneficiary has not yet been implemented")
		}),
		DeleteBeneficiaryByIDHandler: DeleteBeneficiaryByIDHandlerFunc(func(params DeleteBeneficiaryByIDParams) middleware.Responder {
			return middleware.NotImplemented("operation DeleteBeneficiaryByID has not yet been implemented")
		}),
		GenerateOTPHandler: GenerateOTPHandlerFunc(func(params GenerateOTPParams) middleware.Responder {
			return middleware.NotImplemented("operation GenerateOTP has not yet been implemented")
		}),
		GetBeneficiariesHandler: GetBeneficiariesHandlerFunc(func(params GetBeneficiariesParams) middleware.Responder {
			return middleware.NotImplemented("operation GetBeneficiaries has not yet been implemented")
		}),
		GetTimeSlotsHandler: GetTimeSlotsHandlerFunc(func(params GetTimeSlotsParams) middleware.Responder {
			return middleware.NotImplemented("operation GetTimeSlots has not yet been implemented")
		}),
	}
}

/*RegistrationAdapterAPIAPI Registration adapter API */
type RegistrationAdapterAPIAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler
	useSwaggerUI    bool

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator
	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator
	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for the following mime types:
	//   - application/json
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for the following mime types:
	//   - application/json
	JSONProducer runtime.Producer

	// BookAppointmentHandler sets the operation handler for the book appointment operation
	BookAppointmentHandler BookAppointmentHandler
	// CancelAppointmentHandler sets the operation handler for the cancel appointment operation
	CancelAppointmentHandler CancelAppointmentHandler
	// ConfirmOTPHandler sets the operation handler for the confirm o t p operation
	ConfirmOTPHandler ConfirmOTPHandler
	// CreateNewBeneficiaryHandler sets the operation handler for the create new beneficiary operation
	CreateNewBeneficiaryHandler CreateNewBeneficiaryHandler
	// DeleteBeneficiaryByIDHandler sets the operation handler for the delete beneficiary by Id operation
	DeleteBeneficiaryByIDHandler DeleteBeneficiaryByIDHandler
	// GenerateOTPHandler sets the operation handler for the generate o t p operation
	GenerateOTPHandler GenerateOTPHandler
	// GetBeneficiariesHandler sets the operation handler for the get beneficiaries operation
	GetBeneficiariesHandler GetBeneficiariesHandler
	// GetTimeSlotsHandler sets the operation handler for the get time slots operation
	GetTimeSlotsHandler GetTimeSlotsHandler
	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// PreServerShutdown is called before the HTTP(S) server is shutdown
	// This allows for custom functions to get executed before the HTTP(S) server stops accepting traffic
	PreServerShutdown func()

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// UseRedoc for documentation at /docs
func (o *RegistrationAdapterAPIAPI) UseRedoc() {
	o.useSwaggerUI = false
}

// UseSwaggerUI for documentation at /docs
func (o *RegistrationAdapterAPIAPI) UseSwaggerUI() {
	o.useSwaggerUI = true
}

// SetDefaultProduces sets the default produces media type
func (o *RegistrationAdapterAPIAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *RegistrationAdapterAPIAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *RegistrationAdapterAPIAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *RegistrationAdapterAPIAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *RegistrationAdapterAPIAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *RegistrationAdapterAPIAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *RegistrationAdapterAPIAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the RegistrationAdapterAPIAPI
func (o *RegistrationAdapterAPIAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.BookAppointmentHandler == nil {
		unregistered = append(unregistered, "BookAppointmentHandler")
	}
	if o.CancelAppointmentHandler == nil {
		unregistered = append(unregistered, "CancelAppointmentHandler")
	}
	if o.ConfirmOTPHandler == nil {
		unregistered = append(unregistered, "ConfirmOTPHandler")
	}
	if o.CreateNewBeneficiaryHandler == nil {
		unregistered = append(unregistered, "CreateNewBeneficiaryHandler")
	}
	if o.DeleteBeneficiaryByIDHandler == nil {
		unregistered = append(unregistered, "DeleteBeneficiaryByIDHandler")
	}
	if o.GenerateOTPHandler == nil {
		unregistered = append(unregistered, "GenerateOTPHandler")
	}
	if o.GetBeneficiariesHandler == nil {
		unregistered = append(unregistered, "GetBeneficiariesHandler")
	}
	if o.GetTimeSlotsHandler == nil {
		unregistered = append(unregistered, "GetTimeSlotsHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *RegistrationAdapterAPIAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *RegistrationAdapterAPIAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {
	return nil
}

// Authorizer returns the registered authorizer
func (o *RegistrationAdapterAPIAPI) Authorizer() runtime.Authorizer {
	return nil
}

// ConsumersFor gets the consumers for the specified media types.
// MIME type parameters are ignored here.
func (o *RegistrationAdapterAPIAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {
	result := make(map[string]runtime.Consumer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONConsumer
		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result
}

// ProducersFor gets the producers for the specified media types.
// MIME type parameters are ignored here.
func (o *RegistrationAdapterAPIAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {
	result := make(map[string]runtime.Producer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONProducer
		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result
}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *RegistrationAdapterAPIAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the registration adapter API API
func (o *RegistrationAdapterAPIAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *RegistrationAdapterAPIAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened
	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/appointment/schedule"] = NewBookAppointment(o.context, o.BookAppointmentHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/appointment/cancel"] = NewCancelAppointment(o.context, o.CancelAppointmentHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/auth/confirm"] = NewConfirmOTP(o.context, o.ConfirmOTPHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/registration/beneficiaries/new"] = NewCreateNewBeneficiary(o.context, o.CreateNewBeneficiaryHandler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/registration/beneficiaries/{id}"] = NewDeleteBeneficiaryByID(o.context, o.DeleteBeneficiaryByIDHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/auth/generateOTP"] = NewGenerateOTP(o.context, o.GenerateOTPHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/registration/beneficiaries"] = NewGetBeneficiaries(o.context, o.GetBeneficiariesHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/appointment/timeslots/findByCenter"] = NewGetTimeSlots(o.context, o.GetTimeSlotsHandler)
}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *RegistrationAdapterAPIAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	if o.useSwaggerUI {
		return o.context.APIHandlerSwaggerUI(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *RegistrationAdapterAPIAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *RegistrationAdapterAPIAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *RegistrationAdapterAPIAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}

// AddMiddlewareFor adds a http middleware to existing handler
func (o *RegistrationAdapterAPIAPI) AddMiddlewareFor(method, path string, builder middleware.Builder) {
	um := strings.ToUpper(method)
	if path == "/" {
		path = ""
	}
	o.Init()
	if h, ok := o.handlers[um][path]; ok {
		o.handlers[method][path] = builder(h)
	}
}
