// Code generated by go-swagger; DO NOT EDIT.

package configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetConfigurationHandlerFunc turns a function with the right signature into a get configuration handler
type GetConfigurationHandlerFunc func(GetConfigurationParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetConfigurationHandlerFunc) Handle(params GetConfigurationParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetConfigurationHandler interface for that can handle valid get configuration params
type GetConfigurationHandler interface {
	Handle(GetConfigurationParams, interface{}) middleware.Responder
}

// NewGetConfiguration creates a new http.Handler for the get configuration operation
func NewGetConfiguration(ctx *middleware.Context, handler GetConfigurationHandler) *GetConfiguration {
	return &GetConfiguration{Context: ctx, Handler: handler}
}

/*GetConfiguration swagger:route GET /divoc/configuration configuration getConfiguration

Get Meta information about the application flow

*/
type GetConfiguration struct {
	Context *middleware.Context
	Handler GetConfigurationHandler
}

func (o *GetConfiguration) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetConfigurationParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
