// Code generated by go-swagger; DO NOT EDIT.

package login

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/divoc/api/swagger_gen/models"
)

// PostV1AuthorizeOKCode is the HTTP code returned for type PostV1AuthorizeOK
const PostV1AuthorizeOKCode int = 200

/*PostV1AuthorizeOK OK

swagger:response postV1AuthorizeOK
*/
type PostV1AuthorizeOK struct {

	/*
	  In: Body
	*/
	Payload *models.LoginResponse `json:"body,omitempty"`
}

// NewPostV1AuthorizeOK creates PostV1AuthorizeOK with default headers values
func NewPostV1AuthorizeOK() *PostV1AuthorizeOK {

	return &PostV1AuthorizeOK{}
}

// WithPayload adds the payload to the post v1 authorize o k response
func (o *PostV1AuthorizeOK) WithPayload(payload *models.LoginResponse) *PostV1AuthorizeOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post v1 authorize o k response
func (o *PostV1AuthorizeOK) SetPayload(payload *models.LoginResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostV1AuthorizeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostV1AuthorizePartialContentCode is the HTTP code returned for type PostV1AuthorizePartialContent
const PostV1AuthorizePartialContentCode int = 206

/*PostV1AuthorizePartialContent Need otp

swagger:response postV1AuthorizePartialContent
*/
type PostV1AuthorizePartialContent struct {
}

// NewPostV1AuthorizePartialContent creates PostV1AuthorizePartialContent with default headers values
func NewPostV1AuthorizePartialContent() *PostV1AuthorizePartialContent {

	return &PostV1AuthorizePartialContent{}
}

// WriteResponse to the client
func (o *PostV1AuthorizePartialContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(206)
}

// PostV1AuthorizeUnauthorizedCode is the HTTP code returned for type PostV1AuthorizeUnauthorized
const PostV1AuthorizeUnauthorizedCode int = 401

/*PostV1AuthorizeUnauthorized Unauthorized

swagger:response postV1AuthorizeUnauthorized
*/
type PostV1AuthorizeUnauthorized struct {
}

// NewPostV1AuthorizeUnauthorized creates PostV1AuthorizeUnauthorized with default headers values
func NewPostV1AuthorizeUnauthorized() *PostV1AuthorizeUnauthorized {

	return &PostV1AuthorizeUnauthorized{}
}

// WriteResponse to the client
func (o *PostV1AuthorizeUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}
