export const facilities = [
    {
        "serialNum": 100,
        "facilityCode": "DEL010",
        "facilityName": "Awesome Hospital",
        "contact": 9809989981,
        "email": "awesome@mailinator.com",
        "operatingHourStart": 9,
        "operatingHourEnd": 18,
        "category": "GOVT",
        "type": "Fixed location",
        "status": "Active",
        "addressLine1": "No 23",
        "addressLine2": "Road, NIBM Road",
        "district": "Delhi",
        "state": "Delhi",
        "pincode": "A-100001",
        "geoLocationLat": 28,
        "geoLocationLon": 77,
        "websiteURL": "www.awesome.com",
        "adminName": "Suresh",
        "adminMobile": 1111111111
    },
    {
        "serialNum": 101,
        "facilityCode": "BLR311",
        "facilityName": "Chinmaya Mission Hospital",
        "contact": 9876543210,
        "email": "aolo@mailinator.com",
        "operatingHourStart": 10,
        "operatingHourEnd": 17,
        "category": "PRIVATE",
        "type": "Fixed location",
        "status": "Active",
        "addressLine1": "ER34",
        "addressLine2": "My C,D,E",
        "district": "Bengaluru",
        "state": "Karnataka",
        "pincode": "A-560001",
        "geoLocationLat": 13,
        "geoLocationLon": 75,
        "websiteURL": "www.aolo.com",
        "adminName": "ramesh",
        "adminMobile": 1111111112
    },
    {
        "serialNum": 102,
        "facilityCode": "PUN001",
        "facilityName": "Mobile Vaccination Center",
        "contact": 9879879879,
        "email": "mobile@mailinator.com",
        "operatingHourStart": 8,
        "operatingHourEnd": 18,
        "category": "GOVT",
        "type": "Mobile",
        "status": "Active",
        "addressLine1": "PU34",
        "addressLine2": "Road, NIBM Road",
        "district": "Pune",
        "state": "Maharashtra",
        "pincode": "A-5600001",
        "geoLocationLat": "",
        "geoLocationLon": "",
        "websiteURL": "www.mobile.com",
        "adminName": "Mahesh",
        "adminMobile": 1111111113
    },
    {
        "serialNum": 103,
        "facilityCode": "BID001",
        "facilityName": "iCare Hospital",
        "contact": 9876543211,
        "email": "aolo@mailinator.com",
        "operatingHourStart": 10,
        "operatingHourEnd": 17,
        "category": "PRIVATE",
        "type": "Fixed location",
        "status": "Active",
        "addressLine1": "ER34",
        "addressLine2": "My C,D,E",
        "district": "Bidar",
        "state": "Karnataka",
        "pincode": "A-47891",
        "geoLocationLat": 13,
        "geoLocationLon": 33,
        "websiteURL": "www.aolo.com",
        "adminName": "Krishna",
        "adminMobile": 1111111114
    },
    {
        "serialNum": 104,
        "facilityCode": "HYD111",
        "facilityName": "St. Mary’s Medical Center",
        "contact": 9876543212,
        "email": "apollo@mailinator.com",
        "operatingHourStart": 7,
        "operatingHourEnd": 19,
        "category": "GOVT",
        "type": "Fixed location",
        "status": "Active",
        "addressLine1": "OMG 143",
        "addressLine2": "Road, NIBM Road",
        "district": "Hyderabad",
        "state": "Telangana",
        "pincode": "A-100001",
        "geoLocationLat": 28,
        "geoLocationLon": 77,
        "websiteURL": "www.awesome.com",
        "adminName": "Gowri Shankar",
        "adminMobile": 1111111115
    }
]