// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Registration API
//
//  Registration API
//  Schemes:
//    https
//  Host: localhost
//  BasePath: /divoc/api/citizen
//  Version: 1.0.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
