// Code generated by go-swagger; DO NOT EDIT.

package vaccination

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetRecipientsHandlerFunc turns a function with the right signature into a get recipients handler
type GetRecipientsHandlerFunc func(GetRecipientsParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetRecipientsHandlerFunc) Handle(params GetRecipientsParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetRecipientsHandler interface for that can handle valid get recipients params
type GetRecipientsHandler interface {
	Handle(GetRecipientsParams, interface{}) middleware.Responder
}

// NewGetRecipients creates a new http.Handler for the get recipients operation
func NewGetRecipients(ctx *middleware.Context, handler GetRecipientsHandler) *GetRecipients {
	return &GetRecipients{Context: ctx, Handler: handler}
}

/*GetRecipients swagger:route GET /recipients vaccination getRecipients

Fetch waiting recipients

*/
type GetRecipients struct {
	Context *middleware.Context
	Handler GetRecipientsHandler
}

func (o *GetRecipients) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetRecipientsParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
