const REGISTRY_URL = process.env.REGISTRY_URL;
const KEYCLOAK_URL = process.env.KEYCLOAK_URL;
const KEYCLOAK_REALM = 'divoc';
const JWT_PUBLIC_KEY = process.env.AUTH_PUBLIC_KEY;
const KAFKA_BOOTSTRAP_SERVER = process.env.KAFKA_BOOTSTRAP_SERVERS;
const DISEASE_CODE = process.env.DISEASE_CODE;
const PUBLIC_HEALTH_AUTHORITY = process.env.FHIR_PUBLIC_HEALTH_AUTHORITY;
const EU_CERTIFICATE_EXPIRY = parseInt(process.env.EU_CERTIFICATE_EXPIRY);
const SHC_CERTIFICATE_EXPIRY = parseInt(process.env.SHC_CERTIFICATE_EXPIRY);
const CERTIFICATE_ISSUER = process.env.CERTIFICATE_ISSUER;
module.exports = {
    REGISTRY_URL,
    JWT_PUBLIC_KEY,
    KAFKA_BOOTSTRAP_SERVER,
    KEYCLOAK_URL,
    KEYCLOAK_REALM,
    DISEASE_CODE,
    PUBLIC_HEALTH_AUTHORITY,
    EU_CERTIFICATE_EXPIRY,
    SHC_CERTIFICATE_EXPIRY,
    CERTIFICATE_ISSUER
};