const SUNBIRD_REGISTRY_URL = process.env.SUNBIRD_REGISTRY_URL;
const KAFKA_CONSUMER_SESSION_TIMEOUT = process.env.KAFKA_CONSUMER_SESSION_TIMEOUT || 300000;
const VC_CERTIFY_TOPIC = process.env.VC_CERTIFY_TOPIC || 'vc-certify'
const POST_VC_CERTIFY_TOPIC = process.env.POST_VC_CERTIFY_TOPIC || 'post-vc-certify'
const KAFKA_BOOTSTRAP_SERVER = process.env.KAFKA_BOOTSTRAP_SERVERS || 'localhost:9092';
const VC_CERTIFICATION_SERVICE_URL = process.env.VC_CERTIFICATION_SERVICE_URL || 'http://localhost:7654';
module.exports = {
    SUNBIRD_REGISTRY_URL,
    KAFKA_CONSUMER_SESSION_TIMEOUT,
    KAFKA_BOOTSTRAP_SERVER,
    VC_CERTIFY_TOPIC,
    POST_VC_CERTIFY_TOPIC,
    VC_CERTIFICATION_SERVICE_URL
}