export const CONSTANTS = Object.freeze({
    ADMIN_ROLE: "admin",
    ROLE_CONTROLLER: "controller",
    MONITORING: "monitoring",
    FACILITY_ADMIN_ROLE: "facility-admin",
    VACCINATION_CLIENT: "vaccination_api",
    PORTAL_CLIENT: "facility-admin-portal",
});

export const PROGRAMS = ['C-19 Program'];

export const STATE_NAMES = {
    AP: 'Andhra Pradesh',
    AR: 'Arunachal Pradesh',
    AS: 'Assam',
    BR: 'Bihar',
    CT: 'Chhattisgarh',
    GA: 'Goa',
    GJ: 'Gujarat',
    HR: 'Haryana',
    HP: 'Himachal Pradesh',
    JH: 'Jharkhand',
    KA: 'Karnataka',
    KL: 'Kerala',
    MP: 'Madhya Pradesh',
    MH: 'Maharashtra',
    MN: 'Manipur',
    ML: 'Meghalaya',
    MZ: 'Mizoram',
    NL: 'Nagaland',
    OR: 'Odisha',
    PB: 'Punjab',
    RJ: 'Rajasthan',
    SK: 'Sikkim',
    TN: 'Tamil Nadu',
    TG: 'Telangana',
    TR: 'Tripura',
    UT: 'Uttarakhand',
    UP: 'Uttar Pradesh',
    WB: 'West Bengal',
    AN: 'Andaman and Nicobar Islands',
    CH: 'Chandigarh',
    DN: 'Dadra and Nagar Haveli and Daman and Diu',
    DL: 'Delhi',
    JK: 'Jammu and Kashmir',
    LA: 'Ladakh',
    LD: 'Lakshadweep',
    PY: 'Puducherry',
    TT: 'All of India',
};


export const DISTRICT_NAMES = {
    'Bagalkote': 10000,
    'Ballari': 10000,
    'Belagavi': 10000,
    'Bengaluru Rural': 1000,
    'Bengaluru Urban': 10000,
    'Bidar': 10000,
    'Chamarajanagara': 10000,
    'Chikkaballapura': 10000,
    'Chikkamagaluru': 10000,
    'Chitradurga': 10000,
    'Dakshina Kannada': 10000,
    'Davanagere': 10000,
    'Dharwad': 10000,
    'Gadag': 10000,
    'Hassan': 10000,
    'Haveri': 10000,
    'Kalaburagi': 10000,
    'Kodagu': 10000,
    'Kolar': 10000,
    'Koppal': 10000,
    'Mandya': 10000,
    'Mysuru': 10000,
    'Other State': 10000,
    'Raichur': 10000,
    'Ramanagara': 10000,
    'Shivamogga': 10000,
    'Tumakuru': 10000,
    'Udupi': 10000,
    'Uttara Kannada	': 10000,
    ' Vijayapura': 10000,
    'Yadgir': 10000
}
