export const facilities = [
    {
        "serialNum": 100,
        "facilityCode": "DEL010",
        "facilityName": "Awesome Hospital",
        "contact": 9809989981,
        "email": "awesome@mailinator.com",
        "operatingHourStart": 9,
        "operatingHourEnd": 18,
        "category": "GOVT",
        "type": "Fixed location",
        "status": "Active",
        "addressLine1": "No 23",
        "addressLine2": "Road, NIBM Road",
        "district": "Delhi",
        "state": "Delhi",
        "pincode": "A-100001",
        "geoLocationLat": 28,
        "geoLocationLon": 77,
        "websiteURL": "www.awesome.com",
        "adminName": "Suresh",
        "adminMobile": 1111111111
    },
    {
        "serialNum": 101,
        "facilityCode": "BLR311",
        "facilityName": "Chinmaya Mission Hospital",
        "contact": 9876543210,
        "email": "aolo@mailinator.com",
        "operatingHourStart": 10,
        "operatingHourEnd": 17,
        "category": "PRIVATE",
        "type": "Fixed location",
        "status": "Active",
        "addressLine1": "ER34",
        "addressLine2": "My C,D,E",
        "district": "Bengaluru",
        "state": "Karnataka",
        "pincode": "A-560001",
        "geoLocationLat": 13,
        "geoLocationLon": 75,
        "websiteURL": "www.aolo.com",
        "adminName": "ramesh",
        "adminMobile": 1111111112
    }
]