// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// CreateFacilityStaffsOKCode is the HTTP code returned for type CreateFacilityStaffsOK
const CreateFacilityStaffsOKCode int = 200

/*CreateFacilityStaffsOK OK

swagger:response createFacilityStaffsOK
*/
type CreateFacilityStaffsOK struct {
}

// NewCreateFacilityStaffsOK creates CreateFacilityStaffsOK with default headers values
func NewCreateFacilityStaffsOK() *CreateFacilityStaffsOK {

	return &CreateFacilityStaffsOK{}
}

// WriteResponse to the client
func (o *CreateFacilityStaffsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// CreateFacilityStaffsBadRequestCode is the HTTP code returned for type CreateFacilityStaffsBadRequest
const CreateFacilityStaffsBadRequestCode int = 400

/*CreateFacilityStaffsBadRequest Invalid input

swagger:response createFacilityStaffsBadRequest
*/
type CreateFacilityStaffsBadRequest struct {
}

// NewCreateFacilityStaffsBadRequest creates CreateFacilityStaffsBadRequest with default headers values
func NewCreateFacilityStaffsBadRequest() *CreateFacilityStaffsBadRequest {

	return &CreateFacilityStaffsBadRequest{}
}

// WriteResponse to the client
func (o *CreateFacilityStaffsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// CreateFacilityStaffsUnauthorizedCode is the HTTP code returned for type CreateFacilityStaffsUnauthorized
const CreateFacilityStaffsUnauthorizedCode int = 401

/*CreateFacilityStaffsUnauthorized Unauthorized

swagger:response createFacilityStaffsUnauthorized
*/
type CreateFacilityStaffsUnauthorized struct {
}

// NewCreateFacilityStaffsUnauthorized creates CreateFacilityStaffsUnauthorized with default headers values
func NewCreateFacilityStaffsUnauthorized() *CreateFacilityStaffsUnauthorized {

	return &CreateFacilityStaffsUnauthorized{}
}

// WriteResponse to the client
func (o *CreateFacilityStaffsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}
