// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetMedicinesHandlerFunc turns a function with the right signature into a get medicines handler
type GetMedicinesHandlerFunc func(GetMedicinesParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetMedicinesHandlerFunc) Handle(params GetMedicinesParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetMedicinesHandler interface for that can handle valid get medicines params
type GetMedicinesHandler interface {
	Handle(GetMedicinesParams, interface{}) middleware.Responder
}

// NewGetMedicines creates a new http.Handler for the get medicines operation
func NewGetMedicines(ctx *middleware.Context, handler GetMedicinesHandler) *GetMedicines {
	return &GetMedicines{Context: ctx, Handler: handler}
}

/*GetMedicines swagger:route GET /medicines getMedicines

Get medicines

*/
type GetMedicines struct {
	Context *middleware.Context
	Handler GetMedicinesHandler
}

func (o *GetMedicines) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetMedicinesParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
