// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/divoc/portal-api/swagger_gen/models"
)

// GetFacilityStaffsOKCode is the HTTP code returned for type GetFacilityStaffsOK
const GetFacilityStaffsOKCode int = 200

/*GetFacilityStaffsOK OK

swagger:response getFacilityStaffsOK
*/
type GetFacilityStaffsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.FacilityStaff `json:"body,omitempty"`
}

// NewGetFacilityStaffsOK creates GetFacilityStaffsOK with default headers values
func NewGetFacilityStaffsOK() *GetFacilityStaffsOK {

	return &GetFacilityStaffsOK{}
}

// WithPayload adds the payload to the get facility staffs o k response
func (o *GetFacilityStaffsOK) WithPayload(payload []*models.FacilityStaff) *GetFacilityStaffsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get facility staffs o k response
func (o *GetFacilityStaffsOK) SetPayload(payload []*models.FacilityStaff) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetFacilityStaffsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.FacilityStaff, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
