// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/divoc/portal-api/swagger_gen/models"
)

// PostEnrollmentsHandlerFunc turns a function with the right signature into a post enrollments handler
type PostEnrollmentsHandlerFunc func(PostEnrollmentsParams, *models.JWTClaimBody) middleware.Responder

// Handle executing the request and returning a response
func (fn PostEnrollmentsHandlerFunc) Handle(params PostEnrollmentsParams, principal *models.JWTClaimBody) middleware.Responder {
	return fn(params, principal)
}

// PostEnrollmentsHandler interface for that can handle valid post enrollments params
type PostEnrollmentsHandler interface {
	Handle(PostEnrollmentsParams, *models.JWTClaimBody) middleware.Responder
}

// NewPostEnrollments creates a new http.Handler for the post enrollments operation
func NewPostEnrollments(ctx *middleware.Context, handler PostEnrollmentsHandler) *PostEnrollments {
	return &PostEnrollments{Context: ctx, Handler: handler}
}

/*PostEnrollments swagger:route POST /enrollments postEnrollments

Upload facility csv for bulk ingestion of pre enrollment

*/
type PostEnrollments struct {
	Context *middleware.Context
	Handler PostEnrollmentsHandler
}

func (o *PostEnrollments) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostEnrollmentsParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.JWTClaimBody
	if uprinc != nil {
		principal = uprinc.(*models.JWTClaimBody) // this is really a models.JWTClaimBody, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
