// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostVaccinatorsHandlerFunc turns a function with the right signature into a post vaccinators handler
type PostVaccinatorsHandlerFunc func(PostVaccinatorsParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostVaccinatorsHandlerFunc) Handle(params PostVaccinatorsParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostVaccinatorsHandler interface for that can handle valid post vaccinators params
type PostVaccinatorsHandler interface {
	Handle(PostVaccinatorsParams, interface{}) middleware.Responder
}

// NewPostVaccinators creates a new http.Handler for the post vaccinators operation
func NewPostVaccinators(ctx *middleware.Context, handler PostVaccinatorsHandler) *PostVaccinators {
	return &PostVaccinators{Context: ctx, Handler: handler}
}

/*PostVaccinators swagger:route POST /vaccinators postVaccinators

Upload facility csv for bulk ingestion

*/
type PostVaccinators struct {
	Context *middleware.Context
	Handler PostVaccinatorsHandler
}

func (o *PostVaccinators) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostVaccinatorsParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
