// Code generated by go-swagger; DO NOT EDIT.

package certification

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetCertificateByCertificateIDOKCode is the HTTP code returned for type GetCertificateByCertificateIDOK
const GetCertificateByCertificateIDOKCode int = 200

/*GetCertificateByCertificateIDOK OK

swagger:response getCertificateByCertificateIdOK
*/
type GetCertificateByCertificateIDOK struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewGetCertificateByCertificateIDOK creates GetCertificateByCertificateIDOK with default headers values
func NewGetCertificateByCertificateIDOK() *GetCertificateByCertificateIDOK {

	return &GetCertificateByCertificateIDOK{}
}

// WithPayload adds the payload to the get certificate by certificate Id o k response
func (o *GetCertificateByCertificateIDOK) WithPayload(payload interface{}) *GetCertificateByCertificateIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get certificate by certificate Id o k response
func (o *GetCertificateByCertificateIDOK) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCertificateByCertificateIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetCertificateByCertificateIDNotFoundCode is the HTTP code returned for type GetCertificateByCertificateIDNotFound
const GetCertificateByCertificateIDNotFoundCode int = 404

/*GetCertificateByCertificateIDNotFound certificate for given certificateId not found

swagger:response getCertificateByCertificateIdNotFound
*/
type GetCertificateByCertificateIDNotFound struct {
}

// NewGetCertificateByCertificateIDNotFound creates GetCertificateByCertificateIDNotFound with default headers values
func NewGetCertificateByCertificateIDNotFound() *GetCertificateByCertificateIDNotFound {

	return &GetCertificateByCertificateIDNotFound{}
}

// WriteResponse to the client
func (o *GetCertificateByCertificateIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
