// Code generated by go-swagger; DO NOT EDIT.

package symptoms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetInstructionsOKCode is the HTTP code returned for type GetInstructionsOK
const GetInstructionsOKCode int = 200

/*GetInstructionsOK OK

swagger:response getInstructionsOK
*/
type GetInstructionsOK struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewGetInstructionsOK creates GetInstructionsOK with default headers values
func NewGetInstructionsOK() *GetInstructionsOK {

	return &GetInstructionsOK{}
}

// WithPayload adds the payload to the get instructions o k response
func (o *GetInstructionsOK) WithPayload(payload interface{}) *GetInstructionsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get instructions o k response
func (o *GetInstructionsOK) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetInstructionsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
