// Code generated by go-swagger; DO NOT EDIT.

package side_effects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetSideEffectsMetadataOKCode is the HTTP code returned for type GetSideEffectsMetadataOK
const GetSideEffectsMetadataOKCode int = 200

/*GetSideEffectsMetadataOK OK

swagger:response getSideEffectsMetadataOK
*/
type GetSideEffectsMetadataOK struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewGetSideEffectsMetadataOK creates GetSideEffectsMetadataOK with default headers values
func NewGetSideEffectsMetadataOK() *GetSideEffectsMetadataOK {

	return &GetSideEffectsMetadataOK{}
}

// WithPayload adds the payload to the get side effects metadata o k response
func (o *GetSideEffectsMetadataOK) WithPayload(payload interface{}) *GetSideEffectsMetadataOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get side effects metadata o k response
func (o *GetSideEffectsMetadataOK) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSideEffectsMetadataOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
