const SUNBIRD_REGISTRY_URL = process.env.SUNBIRD_REGISTRY_URL;
const SUNBIRD_REGISTRY_TOKEN = process.env.SUNBIRD_REGISTRY_TOKEN
module.exports = {
    SUNBIRD_REGISTRY_URL,
    SUNBIRD_REGISTRY_TOKEN
}