// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Divoc Portal API
//
//  Digital infra for vaccination certificates
//  Schemes:
//    https
//  Host: divoc.xiv.in
//  BasePath: /divoc/admin/api/v1
//  Version: 1.0.0
//
//  Consumes:
//    - application/json
//    - multipart/form-data
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
