// Code generated by go-swagger; DO NOT EDIT.

package configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/divoc/api/swagger_gen/models"
)

// GetCurrentProgramsOKCode is the HTTP code returned for type GetCurrentProgramsOK
const GetCurrentProgramsOKCode int = 200

/*GetCurrentProgramsOK OK

swagger:response getCurrentProgramsOK
*/
type GetCurrentProgramsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Program `json:"body,omitempty"`
}

// NewGetCurrentProgramsOK creates GetCurrentProgramsOK with default headers values
func NewGetCurrentProgramsOK() *GetCurrentProgramsOK {

	return &GetCurrentProgramsOK{}
}

// WithPayload adds the payload to the get current programs o k response
func (o *GetCurrentProgramsOK) WithPayload(payload []*models.Program) *GetCurrentProgramsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get current programs o k response
func (o *GetCurrentProgramsOK) SetPayload(payload []*models.Program) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCurrentProgramsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Program, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
