// Code generated by go-swagger; DO NOT EDIT.

package configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
)

// NewGetCurrentProgramsParams creates a new GetCurrentProgramsParams object
//
// There are no default values defined in the spec.
func NewGetCurrentProgramsParams() GetCurrentProgramsParams {

	return GetCurrentProgramsParams{}
}

// GetCurrentProgramsParams contains all the bound params for the get current programs operation
// typically these are obtained from a http.Request
//
// swagger:parameters getCurrentPrograms
type GetCurrentProgramsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetCurrentProgramsParams() beforehand.
func (o *GetCurrentProgramsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
