// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// BookSlotOfFacilityOKCode is the HTTP code returned for type BookSlotOfFacilityOK
const BookSlotOfFacilityOKCode int = 200

/*BookSlotOfFacilityOK OK

swagger:response bookSlotOfFacilityOK
*/
type BookSlotOfFacilityOK struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewBookSlotOfFacilityOK creates BookSlotOfFacilityOK with default headers values
func NewBookSlotOfFacilityOK() *BookSlotOfFacilityOK {

	return &BookSlotOfFacilityOK{}
}

// WithPayload adds the payload to the book slot of facility o k response
func (o *BookSlotOfFacilityOK) WithPayload(payload interface{}) *BookSlotOfFacilityOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the book slot of facility o k response
func (o *BookSlotOfFacilityOK) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *BookSlotOfFacilityOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// BookSlotOfFacilityBadRequestCode is the HTTP code returned for type BookSlotOfFacilityBadRequest
const BookSlotOfFacilityBadRequestCode int = 400

/*BookSlotOfFacilityBadRequest Bad Request

swagger:response bookSlotOfFacilityBadRequest
*/
type BookSlotOfFacilityBadRequest struct {
}

// NewBookSlotOfFacilityBadRequest creates BookSlotOfFacilityBadRequest with default headers values
func NewBookSlotOfFacilityBadRequest() *BookSlotOfFacilityBadRequest {

	return &BookSlotOfFacilityBadRequest{}
}

// WriteResponse to the client
func (o *BookSlotOfFacilityBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// BookSlotOfFacilityUnauthorizedCode is the HTTP code returned for type BookSlotOfFacilityUnauthorized
const BookSlotOfFacilityUnauthorizedCode int = 401

/*BookSlotOfFacilityUnauthorized Unauthorized

swagger:response bookSlotOfFacilityUnauthorized
*/
type BookSlotOfFacilityUnauthorized struct {
}

// NewBookSlotOfFacilityUnauthorized creates BookSlotOfFacilityUnauthorized with default headers values
func NewBookSlotOfFacilityUnauthorized() *BookSlotOfFacilityUnauthorized {

	return &BookSlotOfFacilityUnauthorized{}
}

// WriteResponse to the client
func (o *BookSlotOfFacilityUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}
