// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteAppointmentOKCode is the HTTP code returned for type DeleteAppointmentOK
const DeleteAppointmentOKCode int = 200

/*DeleteAppointmentOK OK

swagger:response deleteAppointmentOK
*/
type DeleteAppointmentOK struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewDeleteAppointmentOK creates DeleteAppointmentOK with default headers values
func NewDeleteAppointmentOK() *DeleteAppointmentOK {

	return &DeleteAppointmentOK{}
}

// WithPayload adds the payload to the delete appointment o k response
func (o *DeleteAppointmentOK) WithPayload(payload interface{}) *DeleteAppointmentOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete appointment o k response
func (o *DeleteAppointmentOK) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteAppointmentOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// DeleteAppointmentBadRequestCode is the HTTP code returned for type DeleteAppointmentBadRequest
const DeleteAppointmentBadRequestCode int = 400

/*DeleteAppointmentBadRequest Bad Request

swagger:response deleteAppointmentBadRequest
*/
type DeleteAppointmentBadRequest struct {

	/*
	  In: Body
	*/
	Payload *DeleteAppointmentBadRequestBody `json:"body,omitempty"`
}

// NewDeleteAppointmentBadRequest creates DeleteAppointmentBadRequest with default headers values
func NewDeleteAppointmentBadRequest() *DeleteAppointmentBadRequest {

	return &DeleteAppointmentBadRequest{}
}

// WithPayload adds the payload to the delete appointment bad request response
func (o *DeleteAppointmentBadRequest) WithPayload(payload *DeleteAppointmentBadRequestBody) *DeleteAppointmentBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete appointment bad request response
func (o *DeleteAppointmentBadRequest) SetPayload(payload *DeleteAppointmentBadRequestBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteAppointmentBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteAppointmentUnauthorizedCode is the HTTP code returned for type DeleteAppointmentUnauthorized
const DeleteAppointmentUnauthorizedCode int = 401

/*DeleteAppointmentUnauthorized Unauthorized

swagger:response deleteAppointmentUnauthorized
*/
type DeleteAppointmentUnauthorized struct {
}

// NewDeleteAppointmentUnauthorized creates DeleteAppointmentUnauthorized with default headers values
func NewDeleteAppointmentUnauthorized() *DeleteAppointmentUnauthorized {

	return &DeleteAppointmentUnauthorized{}
}

// WriteResponse to the client
func (o *DeleteAppointmentUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}
