// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/divoc/registration-api/swagger_gen/models"
)

// DeleteRecipientHandlerFunc turns a function with the right signature into a delete recipient handler
type DeleteRecipientHandlerFunc func(DeleteRecipientParams, *models.JWTClaimBody) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteRecipientHandlerFunc) Handle(params DeleteRecipientParams, principal *models.JWTClaimBody) middleware.Responder {
	return fn(params, principal)
}

// DeleteRecipientHandler interface for that can handle valid delete recipient params
type DeleteRecipientHandler interface {
	Handle(DeleteRecipientParams, *models.JWTClaimBody) middleware.Responder
}

// NewDeleteRecipient creates a new http.Handler for the delete recipient operation
func NewDeleteRecipient(ctx *middleware.Context, handler DeleteRecipientHandler) *DeleteRecipient {
	return &DeleteRecipient{Context: ctx, Handler: handler}
}

/*DeleteRecipient swagger:route DELETE /recipients deleteRecipient

Delete the recipient

*/
type DeleteRecipient struct {
	Context *middleware.Context
	Handler DeleteRecipientHandler
}

func (o *DeleteRecipient) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteRecipientParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.JWTClaimBody
	if uprinc != nil {
		principal = uprinc.(*models.JWTClaimBody) // this is really a models.JWTClaimBody, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// DeleteRecipientBadRequestBody delete recipient bad request body
//
// swagger:model DeleteRecipientBadRequestBody
type DeleteRecipientBadRequestBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this delete recipient bad request body
func (o *DeleteRecipientBadRequestBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DeleteRecipientBadRequestBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteRecipientBadRequestBody) UnmarshalBinary(b []byte) error {
	var res DeleteRecipientBadRequestBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// DeleteRecipientBody delete recipient body
//
// swagger:model DeleteRecipientBody
type DeleteRecipientBody struct {

	// enrollment code
	// Required: true
	EnrollmentCode *string `json:"enrollmentCode"`

	// enrollment osid
	// Required: true
	EnrollmentOsid *string `json:"enrollmentOsid"`
}

// Validate validates this delete recipient body
func (o *DeleteRecipientBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateEnrollmentCode(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateEnrollmentOsid(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteRecipientBody) validateEnrollmentCode(formats strfmt.Registry) error {

	if err := validate.Required("body"+"."+"enrollmentCode", "body", o.EnrollmentCode); err != nil {
		return err
	}

	return nil
}

func (o *DeleteRecipientBody) validateEnrollmentOsid(formats strfmt.Registry) error {

	if err := validate.Required("body"+"."+"enrollmentOsid", "body", o.EnrollmentOsid); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *DeleteRecipientBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteRecipientBody) UnmarshalBinary(b []byte) error {
	var res DeleteRecipientBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
