// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"
)

// DeleteRecipientProgramURL generates an URL for the delete recipient program operation
type DeleteRecipientProgramURL struct {
	EnrollmentOsid string
	ProgramID      string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *DeleteRecipientProgramURL) WithBasePath(bp string) *DeleteRecipientProgramURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *DeleteRecipientProgramURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *DeleteRecipientProgramURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/recipient/{enrollment_osid}/program/{program_id}/"

	enrollmentOsid := o.EnrollmentOsid
	if enrollmentOsid != "" {
		_path = strings.Replace(_path, "{enrollment_osid}", enrollmentOsid, -1)
	} else {
		return nil, errors.New("enrollmentOsid is required on DeleteRecipientProgramURL")
	}

	programID := o.ProgramID
	if programID != "" {
		_path = strings.Replace(_path, "{program_id}", programID, -1)
	} else {
		return nil, errors.New("programId is required on DeleteRecipientProgramURL")
	}

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/divoc/api/citizen"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *DeleteRecipientProgramURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *DeleteRecipientProgramURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *DeleteRecipientProgramURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on DeleteRecipientProgramURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on DeleteRecipientProgramURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *DeleteRecipientProgramURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
