// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/divoc/registration-api/swagger_gen/models"
)

// GetRecipientsOKCode is the HTTP code returned for type GetRecipientsOK
const GetRecipientsOKCode int = 200

/*GetRecipientsOK OK

swagger:response getRecipientsOK
*/
type GetRecipientsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Enrollment `json:"body,omitempty"`
}

// NewGetRecipientsOK creates GetRecipientsOK with default headers values
func NewGetRecipientsOK() *GetRecipientsOK {

	return &GetRecipientsOK{}
}

// WithPayload adds the payload to the get recipients o k response
func (o *GetRecipientsOK) WithPayload(payload []*models.Enrollment) *GetRecipientsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get recipients o k response
func (o *GetRecipientsOK) SetPayload(payload []*models.Enrollment) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRecipientsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Enrollment, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetRecipientsUnauthorizedCode is the HTTP code returned for type GetRecipientsUnauthorized
const GetRecipientsUnauthorizedCode int = 401

/*GetRecipientsUnauthorized Invalid token

swagger:response getRecipientsUnauthorized
*/
type GetRecipientsUnauthorized struct {
}

// NewGetRecipientsUnauthorized creates GetRecipientsUnauthorized with default headers values
func NewGetRecipientsUnauthorized() *GetRecipientsUnauthorized {

	return &GetRecipientsUnauthorized{}
}

// WriteResponse to the client
func (o *GetRecipientsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// GetRecipientsInternalServerErrorCode is the HTTP code returned for type GetRecipientsInternalServerError
const GetRecipientsInternalServerErrorCode int = 500

/*GetRecipientsInternalServerError Something went wrong

swagger:response getRecipientsInternalServerError
*/
type GetRecipientsInternalServerError struct {
}

// NewGetRecipientsInternalServerError creates GetRecipientsInternalServerError with default headers values
func NewGetRecipientsInternalServerError() *GetRecipientsInternalServerError {

	return &GetRecipientsInternalServerError{}
}

// WriteResponse to the client
func (o *GetRecipientsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
