// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// InitializeFacilitySlotsOKCode is the HTTP code returned for type InitializeFacilitySlotsOK
const InitializeFacilitySlotsOKCode int = 200

/*InitializeFacilitySlotsOK OK

swagger:response initializeFacilitySlotsOK
*/
type InitializeFacilitySlotsOK struct {
}

// NewInitializeFacilitySlotsOK creates InitializeFacilitySlotsOK with default headers values
func NewInitializeFacilitySlotsOK() *InitializeFacilitySlotsOK {

	return &InitializeFacilitySlotsOK{}
}

// WriteResponse to the client
func (o *InitializeFacilitySlotsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// InitializeFacilitySlotsUnauthorizedCode is the HTTP code returned for type InitializeFacilitySlotsUnauthorized
const InitializeFacilitySlotsUnauthorizedCode int = 401

/*InitializeFacilitySlotsUnauthorized Unauthorized

swagger:response initializeFacilitySlotsUnauthorized
*/
type InitializeFacilitySlotsUnauthorized struct {
}

// NewInitializeFacilitySlotsUnauthorized creates InitializeFacilitySlotsUnauthorized with default headers values
func NewInitializeFacilitySlotsUnauthorized() *InitializeFacilitySlotsUnauthorized {

	return &InitializeFacilitySlotsUnauthorized{}
}

// WriteResponse to the client
func (o *InitializeFacilitySlotsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}
