// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// MosipKYCOKCode is the HTTP code returned for type MosipKYCOK
const MosipKYCOKCode int = 200

/*MosipKYCOK OK

swagger:response mosipKYCOK
*/
type MosipKYCOK struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewMosipKYCOK creates MosipKYCOK with default headers values
func NewMosipKYCOK() *MosipKYCOK {

	return &MosipKYCOK{}
}

// WithPayload adds the payload to the mosip k y c o k response
func (o *MosipKYCOK) WithPayload(payload interface{}) *MosipKYCOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the mosip k y c o k response
func (o *MosipKYCOK) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *MosipKYCOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// MosipKYCBadRequestCode is the HTTP code returned for type MosipKYCBadRequest
const MosipKYCBadRequestCode int = 400

/*MosipKYCBadRequest Bad request

swagger:response mosipKYCBadRequest
*/
type MosipKYCBadRequest struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewMosipKYCBadRequest creates MosipKYCBadRequest with default headers values
func NewMosipKYCBadRequest() *MosipKYCBadRequest {

	return &MosipKYCBadRequest{}
}

// WithPayload adds the payload to the mosip k y c bad request response
func (o *MosipKYCBadRequest) WithPayload(payload interface{}) *MosipKYCBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the mosip k y c bad request response
func (o *MosipKYCBadRequest) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *MosipKYCBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// MosipKYCInternalServerErrorCode is the HTTP code returned for type MosipKYCInternalServerError
const MosipKYCInternalServerErrorCode int = 500

/*MosipKYCInternalServerError Internal Error

swagger:response mosipKYCInternalServerError
*/
type MosipKYCInternalServerError struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewMosipKYCInternalServerError creates MosipKYCInternalServerError with default headers values
func NewMosipKYCInternalServerError() *MosipKYCInternalServerError {

	return &MosipKYCInternalServerError{}
}

// WithPayload adds the payload to the mosip k y c internal server error response
func (o *MosipKYCInternalServerError) WithPayload(payload interface{}) *MosipKYCInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the mosip k y c internal server error response
func (o *MosipKYCInternalServerError) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *MosipKYCInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
