// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// FacilityStaff facility staff
//
// swagger:model FacilityStaff
type FacilityStaff struct {

	// Facility Staff Id
	EmployeeID string `json:"employeeId,omitempty"`

	// Facility Staff Mobile Number
	MobileNumber string `json:"mobileNumber,omitempty"`

	// Facility Staff Name
	Name string `json:"name,omitempty"`

	// Facility Staff Role ID
	RoleID string `json:"roleId,omitempty"`
}

// Validate validates this facility staff
func (m *FacilityStaff) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *FacilityStaff) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FacilityStaff) UnmarshalBinary(b []byte) error {
	var res FacilityStaff
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
