swagger: "2.0"
info:
  title: Registration API
  description: Registration API
  version: 1.0.0
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
  hasRole:
    type: oauth2
    flow: accessCode
    authorizationUrl: 'https://divoc.xiv.in/keycloak/auth/realms/divoc/protocol/openid-connect/auth'
    tokenUrl: 'https://divoc.xiv.in/keycloak/auth/realms/divoc/protocol/openid-connect/token'
    scopes:
      facility-admin: scope of facility admin
schemes:
  - https
basePath: /divoc/api/citizen
consumes:
  - application/json
produces:
  - application/json
paths:
  /appointment:
    delete:
      summary: Delete the appointment
      operationId: deleteAppointment
      security:
       - Bearer: [ ]
      parameters:
        - in: body
          name: body
          schema:
            type: object
            required:
              - enrollmentCode
              - programId
              - dose
            properties:
              enrollmentCode:
                type: string
              programId:
                type: string
              dose:
                type: string
      responses:
        '200':
          description: OK
          schema:
            type: object
        '400':
          description: Bad Request
          schema:
            type: object
            properties:
              message:
                type: string
        '401':
          description: Unauthorized
    post:
      summary: Book a slot in facility
      operationId: bookSlotOfFacility
      security:
        - Bearer: [ ]
      parameters:
        - in: body
          name: body
          schema:
            type: object
            required:
              - facilitySlotId
              - enrollmentCode
              - programId
              - dose
            properties:
              facilitySlotId:
                type: string
              enrollmentCode:
                type: string
              programId:
                type: string
              dose:
                type: string
      responses:
        '200':
          description: OK
          schema:
            type: object
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
  /config/{key}:
    get:
      summary: get config
      operationId: getConfig
      parameters:
        - in: path
          name: key
          type: string
          required: true
          description: key in etcd
      security:
        - Bearer: [ ]
      responses:
        '200':
          description: OK
          schema:
            type: object
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
  /facility/slots:
    get:
      summary: Get slots for facilites
      operationId: getSlotsForFacilities
      security:
        - Bearer: [ ]
      parameters:
        - in: query
          name: programId
          type: string
        - in: query
          name: facilityId
          type: string
        - in: query
          name: pageNumber
          type: integer
          default: 0
        - in: query
          name: pageSize
          type: integer
          default: 0
      responses:
        '200':
          description: OK
          schema:
            type: object
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
  /facility/slots/init:
    post:
      summary: Initialize facility slots
      operationId: initializeFacilitySlots
      security: [ ]
      parameters:
        - in: body
          name: body
          schema:
            type: object
            properties:
              apiKey:
                type: string
        - in: query
          name: force
          type: boolean
          default: false
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
  /recipient/{enrollment_osid}/program/{program_id}/:
    delete:
      summary: Delete the recipient program
      operationId: deleteRecipientProgram
      security:
        - Bearer: [ ]
      parameters:
        - name: program_id
          in: path
          required: true
          type: string
        - name: enrollment_osid
          in: path
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: object
        '400':
          description: Bad Request
        '500':
          description: Internal Error
        '401':
          description: Unauthorized
    post:
      summary: register recipient to program
      operationId: registerRecipientToProgram
      security:
        - Bearer: [ ]
      parameters:
        - name: program_id
          in: path
          required: true
          type: string
        - name: enrollment_osid
          in: path
          required: true
          type: string
        - in: body
          name: body
          schema:
            type: object
            properties:
              comorbidities:
                type: array
                items:
                  type: string
      responses:
        '200':
          description: OK
          schema:
            type: object
        '400':
          description: Bad Request
        '500':
          description: Internal Error
        '401':
          description: Unauthorized

  /recipients:
    delete:
      summary: Delete the recipient
      operationId: deleteRecipient
      security:
        - Bearer: [ ]
      parameters:
        - in: body
          name: body
          schema:
            type: object
            required:
              - enrollmentCode
            properties:
              enrollmentCode:
                type: string
      responses:
        '200':
          description: OK
          schema:
            type: object
        '400':
          description: Bad Request
          schema:
            type: object
            properties:
              message:
                type: string
        '401':
          description: Unauthorized
        '500':
         description: Internal Error
    post:
      summary: Enroll Recipient
      operationId: enrollRecipient
      security:
        - Bearer: [ ]
      parameters:
        - in: body
          name: body
          schema:
            $ref: '../registry/Enrollment.json#/definitions/Enrollment'
          description: Recipient Details
      responses:
        '200':
          description: OK
        '401':
          description: Invalid token
    get:
      summary: Get all the recipients
      operationId: getRecipients
      security:
        - Bearer: [ ]
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              type: object
              $ref: '../registry/Enrollment.json#/definitions/Enrollment'
        '401':
          description: Invalid token
        '500':
          description: Something went wrong
  /beneficiaries/search:
    get:
      summary: Get all beneficiaries
      operationId: getBeneficiaries
      security:
        - hasRole: ['facility-admin']
      parameters:
        - in: query
          name: programId
          required: true
          type: string
          description: Program Id
        - in: query
          name: startDate
          required: true
          type: string
          format: date
          description: Start Date
        - in: query
          name: endDate
          required: true
          type: string
          format: date
          description: End Date
        - in: query
          name: type
          type: string
          required: true
          enum: ["CERTIFIED", "OPEN_APPOINTMENT", "ALL"]
          description: Facility Type
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              type: object
              $ref: '../registry/Enrollment.json#/definitions/Enrollment'
  /generateOTP:
   post:
     summary: Generate OTP
     operationId: generateOTP
     security: []
     parameters:
       - in: body
         name: body
         required: true
         schema:
          type: object
          properties:
            phone:
              type: string
     responses:
       '200':
         description: OK
       '204':
         description: Phone number is empty
       '500':
         description: Internal Error
       '400':
         description: Bad request
  /external/mosip/generateOTP:
    post:
      summary: Generate OTP
      operationId: mosipGenerateOTP
      security: []
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            required:
              - individualIdType
              - individualId
            properties:
              individualIdType:
                type: string
                enum: ["UIN", "VID"]
              individualId:
                type: string
      responses:
        '200':
          description: OK
        '500':
          description: Internal Error
        '400':
          description: Bad request
  /verifyOTP:
    post:
      summary: Verify OTP
      operationId: verifyOTP
      security: []
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              phone:
                type: string
              otp:
                type: string
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              token:
                type: string
        '401':
          description: Invalid OTP
        '400':
          description: Bad request
        '500':
          description: Internal error
        '429':
          description: Verify otp attempts exceeded, generate new OTP
  /ping:
    get:
      summary: Server heartbeat operation
      description: >-
        This operation shows how to override the global security defined above,
        as we want to open it up for all users.
      security: []
      responses:
        '200':
          description: OK
