// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// FacilityUser facility user
//
// swagger:model FacilityUser
type FacilityUser struct {

	// Email of User
	Email string `json:"email,omitempty"`

	// Facility User Id
	EmployeeID string `json:"employeeId,omitempty"`

	// enable/disable user
	Enabled bool `json:"enabled,omitempty"`

	// groups
	Groups []*UserGroup `json:"groups"`

	// Facility User Id
	ID string `json:"id,omitempty"`

	// Facility User Mobile Number
	MobileNumber string `json:"mobileNumber,omitempty"`

	// Facility User Name
	Name string `json:"name,omitempty"`

	// Osid of the user stored in Facility Entity
	Osid string `json:"osid,omitempty"`

	// vaccination rate limits
	VaccinationRateLimits []*VaccinationRateLimit `json:"vaccinationRateLimits"`
}

// Validate validates this facility user
func (m *FacilityUser) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateGroups(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVaccinationRateLimits(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *FacilityUser) validateGroups(formats strfmt.Registry) error {
	if swag.IsZero(m.Groups) { // not required
		return nil
	}

	for i := 0; i < len(m.Groups); i++ {
		if swag.IsZero(m.Groups[i]) { // not required
			continue
		}

		if m.Groups[i] != nil {
			if err := m.Groups[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("groups" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *FacilityUser) validateVaccinationRateLimits(formats strfmt.Registry) error {
	if swag.IsZero(m.VaccinationRateLimits) { // not required
		return nil
	}

	for i := 0; i < len(m.VaccinationRateLimits); i++ {
		if swag.IsZero(m.VaccinationRateLimits[i]) { // not required
			continue
		}

		if m.VaccinationRateLimits[i] != nil {
			if err := m.VaccinationRateLimits[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("vaccinationRateLimits" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this facility user based on the context it is used
func (m *FacilityUser) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateGroups(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateVaccinationRateLimits(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *FacilityUser) contextValidateGroups(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Groups); i++ {

		if m.Groups[i] != nil {
			if err := m.Groups[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("groups" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *FacilityUser) contextValidateVaccinationRateLimits(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.VaccinationRateLimits); i++ {

		if m.VaccinationRateLimits[i] != nil {
			if err := m.VaccinationRateLimits[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("vaccinationRateLimits" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *FacilityUser) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FacilityUser) UnmarshalBinary(b []byte) error {
	var res FacilityUser
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
