// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// FacilityAdmin facility admin
//
// swagger:model FacilityAdmin
type FacilityAdmin struct {

	// Facility Admin Mobile Number
	Mobile string `json:"mobile,omitempty"`

	// Facility Admin Name
	Name string `json:"name,omitempty"`

	// Facility Admin Status
	Status string `json:"status,omitempty"`
}

// Validate validates this facility admin
func (m *FacilityAdmin) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *FacilityAdmin) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FacilityAdmin) UnmarshalBinary(b []byte) error {
	var res FacilityAdmin
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
