const SUNBIRD_REGISTRY_URL = process.env.SUNBIRD_REGISTRY_URL;
const KAFKA_CONSUMER_SESSION_TIMEOUT = process.env.KAFKA_CONSUMER_SESSION_TIMEOUT || 300000;
const POST_CREATE_ENTITY_TOPIC = process.env.POST_CREATE_ENTITY_TOPIC || 'post_create_entity';
const KAFKA_BOOTSTRAP_SERVER = process.env.KAFKA_BOOTSTRAP_SERVERS || 'localhost:9092';
module.exports = {
    SUNBIRD_REGISTRY_URL,
    KAFKA_CONSUMER_SESSION_TIMEOUT,
    POST_CREATE_ENTITY_TOPIC,
    KAFKA_BOOTSTRAP_SERVER
}